name: Makefile CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Deps
      run: |
        sudo apt-get -y install libfuse2

    - name: Build
      run: |
        curl -o apprepo https://github.com/area-of-dev/apprepo.AppImage/releases/download/latest/apprepo.AppImage
        chmod +x apprepo
        PATH=$PATH:$PWD make all

    - name: Release
      uses: actions/upload-artifact@v4.3.0
      with:
        path: '*.AppImage'
        overwrite: true
